# ==============================================================================
#
# Proteus Health Report Configuration
#
# ==============================================================================
# 
# This is the default configuration for the health reporting. Override this with user-level config
# to tweak which sections, hostname, etc. are used for your report.
#
# ==============================================================================
#

[report]
# Sets the name of the host, used for the report title
hostname=My Host

# File where Discord webhook URL is stored
webhook_file="discord-webhook-url.txt"

# Location to save report log file
# Note: ensure the directory exists and is writable
report_file_location="/var/log/health-reports/report.log"

# List of systemd services to monitor
# Health report will show status (active/inactive) for each
# Define this is a comma separated list of entries
services_to_monitor="ssh"

# ==============================================================================

# Report Sections
# Enable or disable specific report sections
[sections]
# Directory size warnings for logs directories
logs_warnings=true

# Directory size warnings for cache directories
caches_warnings=true

# Directory size warnings for temporary directories
temp_warnings=true

# Overall disk usage warning
disk_warnings=true

# Systemctl service status checks
service_statuses=true

# DNS resolution test
dns_resolution=false

# Network statistics with vnstat
net_stats=false

# Docker container status
docker_containers=false

# Power Saving stats
power_saving_stats=false

# ==============================================================================

[networking_reporting]
# Network interfaces to consider for the health report. 
# These must be provided to populate data within the net_stats report section
# Define this is a comma separated list of entries
network_interfaces='eth0'

# Domain(s) to test for DNS resolution
# Define this is a comma separated list of entries
dns_test_domain="google.com"

# ==============================================================================

[file_reporting]
# Disk usage percentage threshold (0-100)
# Report if disk usage exceeds this percentage
disk_percent=50

# File/directory size threshold for warnings
# Format=number with unit (K, M, G)
# Report directories larger than this size
file_size="500M"

# Disk device to monitor
disk_device="/dev/vda1"

# Directories to check for logs size warnings
# Define this is a comma separated list of entries
logs_directories="/var/log/*"

# Directories to check for cache size warnings
# Define this is a comma separated list of entries
cache_directories="/var/cache/*"

# Directories to check for temp size warnings
# Define this is a comma separated list of entries
temp_directories="/tmp/*"

# ==============================================================================

